//ACCESS NUMBER///////////////////////////////////////////////////////////////

export const ACCESS_NUMBER_URL = "/api/access-list/";

export const MODAL_CREATE_OPEN_ACCESS_NUMBER = 'MODAL_CREATE_OPEN_ACCESS_NUMBER';
export const MODAL_CREATE_CLOSE_ACCESS_NUMBER = 'MODAL_CREATE_CLOSE_ACCESS_NUMBER';

export const MODAL_UPDATE_OPEN_ACCESS_NUMBER = 'MODAL_UPDATE_OPEN_ACCESS_NUMBER';
export const MODAL_UPDATE_CLOSE_ACCESS_NUMBER = 'MODAL_UPDATE_CLOSE_ACCESS_NUMBER';

export const GET_ACCESS_NUMBER_REQUEST = 'GET_ACCESS_NUMBER_REQUEST';
export const GET_ACCESS_NUMBER_ERROR = 'GET_ACCESS_NUMBER_ERROR';
export const GET_ACCESS_NUMBER_SUCCESS = 'GET_ACCESS_NUMBER_SUCCESS';

export const CREATE_ACCESS_NUMBER_REQUEST = 'CREATE_ACCESS_NUMBER_REQUEST';
export const CREATE_ACCESS_NUMBER_ERROR = 'CREATE_ACCESS_NUMBER_ERROR';
export const CREATE_ACCESS_NUMBER_SUCCESS = 'CREATE_ACCESS_NUMBER_SUCCESS';

export const DELETE_ACCESS_NUMBER_REQUEST = 'DELETE_ACCESS_NUMBER_REQUEST';
export const DELETE_ACCESS_NUMBER_ERROR = 'DELETE_ACCESS_NUMBER_ERROR';
export const DELETE_ACCESS_NUMBER_SUCCESS = 'DELETE_ACCESS_NUMBER_SUCCESS';

export const UPDATE_ACCESS_NUMBER_REQUEST = 'UPDATE_ACCESS_NUMBER_REQUEST';
export const UPDATE_ACCESS_NUMBER_ERROR = 'UPDATE_ACCESS_NUMBER_ERROR';
export const UPDATE_ACCESS_NUMBER_SUCCESS = 'UPDATE_ACCESS_NUMBER_SUCCESS';

export const LIST_ACCESS_NUMBER_REQUEST = 'LIST_ACCESS_NUMBER_REQUEST';
export const LIST_ACCESS_NUMBER_ERROR = 'LIST_ACCESS_NUMBER_ERROR';
export const LIST_ACCESS_NUMBER_SUCCESS = 'LIST_ACCESS_NUMBER_SUCCESS';

//USER////////////////////////////////////////////////////////////////////////////////


export const MODAL_CREATE_OPEN_USER = 'MODAL_CREATE_OPEN_USER';
export const MODAL_CREATE_CLOSE_USER = 'MODAL_CREATE_CLOSE_USER';

export const MODAL_UPDATE_OPEN_USER = 'MODAL_UPDATE_OPEN_USER';
export const MODAL_UPDATE_CLOSE_USER = 'MODAL_UPDATE_CLOSE_USER';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const LIST_USER_REQUEST = 'LIST_USER_REQUEST';
export const LIST_USER_ERROR = 'LIST_USER_ERROR';
export const LIST_USER_SUCCESS = 'LIST_USER_SUCCESS';

//AUTHENTICATION/////////////////////////////////////////////////////////////////

export const AUTHENTICATION_URL = "/api/login/";
export const AUTHENTICATION_REQUEST = 'AUTHENTICATION_REQUEST';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';


//DETECTION../////////////////////////////////////////////////////////////////////////

export const MODAL_DETECTION_OPEN = "MODAL_DETECTION_OPEN";
export const MODAL_DETECTION_CLOSE = "MODAL_DETECTION_CLOSE";

export const GET_DETECTION_REQUEST = 'GET_DETECTION_REQUEST';
export const GET_DETECTION_ERROR = 'GET_DETECTION_ERROR';
export const GET_DETECTION_SUCCESS = 'GET_DETECTION_SUCCESS';

export const UPDATE_DETECTION_REQUEST = 'UPDATE_DETECTION_REQUEST';
export const UPDATE_DETECTION_ERROR = 'UPDATE_DETECTION_ERROR';
export const UPDATE_DETECTION_SUCCESS = 'UPDATE_DETECTION_SUCCESS';

export const DELETE_DETECTION_REQUEST = 'DELETE_DETECTION_REQUEST';
export const DELETE_DETECTION_ERROR = 'DELETE_DETECTION_ERROR';
export const DELETE_DETECTION_SUCCESS = 'DELETE_DETECTION_SUCCESS';

export const LIST_DETECTION_REQUEST = 'LIST_DETECTION_REQUEST';
export const LIST_DETECTION_ERROR = 'LIST_DETECTION_ERROR';
export const LIST_DETECTION_SUCCESS = 'LIST_DETECTION_SUCCESS';

//CURRENT_USER/////////////////////////////////////////////////////////////////////

export const GET_CURRENT_USER_REQUEST = 'GET_CURRENT_USER_REQUEST';
export const GET_CURRENT_USER_ERROR = 'GET_CURRENT_USER_ERROR';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';


//FUZZY/////////////////////////////////////////////////////////////////////


export const GET_FUZZY_REQUEST = "GET_FUZZY_REQUEST";
export const GET_FUZZY_SUCCESS = "GET_FUZZY_SUCCESS";
export const GET_FUZZY_ERROR = "GET_FUZZY_ERROR";


//CAMERA ROTATTION////////////////////////////////////////////////////////////////

export const CAMERA_ROTATION_REQUEST = "CAMERA_ROTATION_REQUEST";
export const CAMERA_ROTATION_SUCCESS = "CAMERA_ROTATION_SUCCESS";
export const CAMERA_ROTATION_ERROR = "CAMERA_ROTATION_ERROR";
