# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_list', '0002_auto_20170521_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslist',
            name='created',
            field=models.DateTimeField(auto_now=True, max_length=255),
        ),
    ]
